CREATE TABLE "DB7"."RENT_CALL" 
   (	"RC_SENDER" VARCHAR2(10 BYTE), 
	"RC_RECEIVER" VARCHAR2(10 BYTE), 
	"RC_CONTENT" VARCHAR2(1000 BYTE), 
	"RC_READTIME" DATE, 
	"RC_SENDTIME" DATE, 
	"RC_USERNUM" VARCHAR2(10 BYTE), 
	"RC_PRODNUM" NUMBER)
   ) 
   
CREATE TABLE "DB7"."RENT_CARD" 
   (	"RC_CARDNAME" VARCHAR2(100 BYTE), 
	"RC_CARDNUM" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("RC_CARDNUM"))
	 
CREATE TABLE "DB7"."RENT_LIKE_ITEMS" 
   (	"RL_ITEMNUM" NUMBER, 
	"RL_ITEMNAME" VARCHAR2(2000 BYTE), 
	"RL_PRICE" NUMBER, 
	"RL_USERNUM" NUMBER, 
	"RL_STAT" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("RL_ITEMNUM"))
	 
CREATE TABLE "DB7"."RENT_MAINCATE" 
   (	"MAINCATE_CODE" NUMBER, 
	"MAINCATE_VALUE" VARCHAR2(100 BYTE)
   ))
   
CREATE TABLE "DB7"."RENT_ORDERS" 
   (	"RO_ORDERNUM" NUMBER, 
	"RO_USERNUM" NUMBER, 
	"RO_TOTAL" NUMBER, 
	"RO_BYDATE" DATE, 
	 PRIMARY KEY ("RO_ORDERNUM"))   
	 
	 
CREATE TABLE "DB7"."RENT_ORDERS_ITEMS" 
   (	"ROI_ITEMID" NUMBER, 
	"ROI_ORDERNUM" NUMBER, 
	"ROI_ITEMNUM" NUMBER, 
	"ROI_PRICE" NUMBER, 
	"ROI_STARTDATE" DATE, 
	"ROI_ENDDATE" DATE, 
	"ROI_BUYIDNUM" NUMBER, 
	"ROI_SALEIDNUM" NUMBER, 
	"ROI_STAT" VARCHAR2(100 BYTE), 
	"ROI_BUYERNAME" VARCHAR2(100 BYTE), 
	"ROI_BUYERADDRESS" VARCHAR2(300 BYTE), 
	"ROI_BUYERPHONE" VARCHAR2(100 BYTE), 
	"ROI_COMMENT" VARCHAR2(2000 BYTE), 
	 PRIMARY KEY ("ROI_ITEMID")	)
	 

CREATE TABLE "DB7"."RENT_PRODUCTS" 
   (	"RP_ITEMNUM" NUMBER, 
	"RP_ITEMNAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"RP_CATEMAIN" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RP_CATESUB" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RP_PRICE" NUMBER NOT NULL ENABLE, 
	"RP_REGDATE" DATE, 
	"RP_STARTDATE" DATE NOT NULL ENABLE, 
	"RP_ENDDATE" DATE NOT NULL ENABLE, 
	"RP_IMG1" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RP_IMG2" VARCHAR2(100 BYTE), 
	"RP_IMG3" VARCHAR2(100 BYTE), 
	"RP_USERNUM" NUMBER, 
	"RP_DETAIL" VARCHAR2(3000 BYTE), 
	"RP_GURANTEE" VARCHAR2(20 BYTE), 
	"RP_DELAYPRICE" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("RP_ITEMNUM")	 
	 
CREATE TABLE "DB7"."RENT_REVIEW" 
   (	"RR_REVIEWNUM" NUMBER, 
	"RR_ITEMNUM" NUMBER, 
	"RR_USERNUM" NUMBER, 
	"RR_USERID" VARCHAR2(100 BYTE), 
	"RR_SUBJECT" VARCHAR2(300 BYTE), 
	"RR_CONTENT" VARCHAR2(2000 BYTE), 
	"RR_IMG" VARCHAR2(100 BYTE), 
	"RR_REGDATE" DATE, 
	"RR_GRADE" NUMBER, 
	 PRIMARY KEY ("RR_REVIEWNUM")	 
	 
CREATE TABLE "DB7"."RENT_SUBCATE" 
   (	"SUBCATE_CODE" NUMBER, 
	"MAINCATE_CODE" NUMBER, 
	"SUBCATE_VALUE" VARCHAR2(100 BYTE)
   )	 
   

CREATE TABLE "DB7"."RENT_USERS" 
   (	"R_IDNUM" NUMBER, 
	"R_ID" VARCHAR2(50 BYTE), 
	"R_PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"R_NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"R_ADDRESS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"R_PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"R_CARD" VARCHAR2(30 BYTE), 
	"R_CARDNUM" VARCHAR2(120 BYTE), 
	"R_CASH" NUMBER, 
	"R_STAT" VARCHAR2(20 BYTE), 
	"R_REGDATE" DATE, 
	 PRIMARY KEY ("R_IDNUM")   )